name: Test networking
on: [push]

jobs:
  linux:
    runs-on: ubuntu-20.04
    container: seladb/${{ matrix.image }}
    strategy:
      matrix:
        include:
          - image: ubuntu2004
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run
        run: ./run.sh
