version: 1.0.{build}

environment:
  PYTHON: "C:\\Python38-x64"
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      compiler: mingw32

init:
- set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
- install_npcap.bat
- "python -m pip install --upgrade pip"
- "python -m pip install -r requirements.txt"

build_script:
- "python temp.py"

for:
-
  matrix:
    only:
      - compiler: mingw32

  install:
  - python patch_mingw.py
  - git clone https://github.com/seladb/PcapPlusPlus-Deploy
  - cd PcapPlusPlus-Deploy\Packages
  - set PATH=%PATH%;C:\MinGW\bin&& 7z e pthreads-GC-w32-2.10-mingw32-pre-20160821-1-dev.tar.xz -oC:\pthreads && 7z x C:\pthreads\pthreads-GC-w32-2.10-mingw32-pre-20160821-1-dev.tar -oC:\pthreads && xcopy /Y C:\pthreads\include\* C:\MinGW\include && xcopy /Y C:\pthreads\lib\* C:\MinGW\lib
